manipulator:
  joints: ['joint1', 'joint2', 'joint3']
  directions: [1, 1, 1]
  origin: [0.0, 0, 0.2, 0.0, 0.0, 0.0]
  end_effector_offset: [0.0, 0.0, 0.0]
  home: [-0.443, 0.907, -0.463]
  limits:
    upper: [1.57, 1.57, 2.3]
    lower: [-1.57, -1.57, -2.3]
  lambda: 30.0
UAV:
  degrees_of_freedom: 4
  lambda: 30.0
IMPEDANCE_FILTER:
  M: [25, 25, 25, 0.0833333, 0.0833333, 0.0833333]
  B: [100, 100, 100, 0.5270462767, 0.5270462767, 0.5270462767]
  K: [100, 100, 100, 0.83333333 , 0.83333333, 0.83333333]
  dead_zone: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
AIC:
  INTEGRAL_ADAPTATION_GAINS:
    ke1: [0.04, 0.04, 0.04, 0.0, 0.0, 0.0]
  PROPORTIONAL_ADAPTATION_GAINS:
    ke2: [0.1, 0.1, 0.1, 0.0, 0.0, 0.0]
  INITIAL_GAINS:
    Ke: [0.0, 0.0, 0.0, 1.0, 1.0, 1.0]
  WEIGHTING_FACTORS:
    Wp: [1.5, 1.5, 1.5, 0.0, 0.0, 0.0]
    Wd: [0.8, 0.8, 0.8, 0.0, 0.0, 0.0]